---
title: "Billboard"
author: "Amisha Jain"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(billboard)
library(tidyverse)
```


```{r clean_data, echo = FALSE}
x <- wiki_hot_100s |> 
  as_tibble() |> 
  mutate(year = parse_number(year)) 
```


```{r, echo = FALSE}
#some artists appear differently. See `N Sync.
#Which artist appears the most?
temp <- x |> 
  group_by(artist) |> 
  summarise(freq = n()) |> 
  arrange(desc(freq))
```



```{r, echo = FALSE}
temp2 <- x |> 
  group_by(artist) |> 
  summarise(freq = n()) |>
  filter(freq == 1)
```


```{r, echo = FALSE}
#how many distinct artists in a year?
x |> 
  group_by(year) |> 
  distinct(artist) |> 
  summarize(distinct_artists = n()) |> 
  ggplot(aes(x = year, 
             y = distinct_artists, fill = year)) + 
    geom_point(alpha = .5) + 
  theme_classic() +
  labs(title = "Number of Distinct Artists per Year", 
       x = "Year", y = "Number of Distinct Artists", 
       caption= "Source: Wiki_hot_100s")

```

